version: '3'
services:
  app:
    build:
      context: .  # Указывает текущую директорию как контекст сборки
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5452/students  # Используйте порт 5432 внутри контейнера
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: students
    ports:
      - "5452:5432"  # Пробрасывает порт 5452 на хосте на порт 5432 в контейнере
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохраняет данные базы данных

# Определяем том для хранения данных PostgreSQL
volumes:
  postgres_data: